---
kind: pipeline
type: docker
name: code analysis

environment:
  V_CONFIGURATION: Release

clone:
  depth: 5
  skip_verify: true

steps:
- name: pack
  image: local/dotnet/sdk:8.0.0
  commands:
  - |
    dotnet restore
    dotnet pack --configuration $V_CONFIGURATION --no-build --output ./packages -p:IncludeSymbols=true -p:SymbolPackageFormat=symbols.nupkg

- name: publish
  image: local/dotnet/sdk:8.0.0
  commands:
  - |
    for package in ./packages/*.symbols.nupkg
    do
      echo Pushing $package to $NUGET_LOCAL_URI_INTERNAL
      dotnet nuget push $package --source $NUGET_LOCAL_URI_INTERNAL
    done
  depends_on:
  - pack
  when:
    ref:
      include:
      - refs/tags/**